/**
 * Shader Gallery — Core Type Definitions
 *
 * All public interfaces for the shader gallery application.
 * See docs/plans/2026-02-12-shader-gallery-design.md for full spec.
 *
 * @module types
 */

/** Supported external links for a shader entry */
export interface ShaderLinks {
  /** URL to the shader on Shadertoy */
  shadertoy?: string;
  /** URL to the shader on ShaderKit */
  shaderkit?: string;
}

/**
 * Channel binding target.
 * - Buffer pass references: 'buffer-a' through 'buffer-d'
 * - Self-feedback: 'self'
 * - Texture path relative to public/: e.g. 'textures/noise.png'
 */
export type ChannelTarget = 'buffer-a' | 'buffer-b' | 'buffer-c' | 'buffer-d' | 'self' | (string & Record<never, never>);

/** Uniform channel slot names matching Shadertoy convention */
export type ChannelSlot = 'iChannel0' | 'iChannel1' | 'iChannel2' | 'iChannel3';

/** Channel bindings for a single render pass */
export type ChannelBindings = Partial<Record<ChannelSlot, ChannelTarget>>;

/** Render pass identifiers */
export type PassId = 'image' | 'bufferA' | 'bufferB' | 'bufferC' | 'bufferD';

/** Channel configuration for all passes in a shader */
export type ShaderChannels = Partial<Record<PassId, ChannelBindings>>;

/** Shader source code organized by render pass */
export interface ShaderPasses {
  /** Main output pass (always present) */
  image: string;
  /** Buffer A source (optional) */
  bufferA?: string;
  /** Buffer B source (optional) */
  bufferB?: string;
  /** Buffer C source (optional) */
  bufferC?: string;
  /** Buffer D source (optional) */
  bufferD?: string;
}

/** Metadata for a single shader in the gallery */
export interface ShaderMeta {
  /** URL-friendly identifier, derived from folder name */
  slug: string;
  /** Display title */
  title: string;
  /** Brief description of the shader effect */
  description: string;
  /** ISO 8601 date string (YYYY-MM-DD) */
  date: string;
  /** Categorization tags (e.g., "raymarching", "noise") */
  tags: string[];
  /** External links to shader platforms */
  links: ShaderLinks;
}

/** Complete shader entry as generated by the Vite plugin */
export interface ShaderEntry extends ShaderMeta {
  /** Path to the screenshot image */
  screenshotUrl: string;
  /** GLSL source code per render pass */
  passes: ShaderPasses;
  /** Channel wiring between passes */
  channels: ShaderChannels;
}

/** Raw meta.json structure before slug/screenshot are injected */
export interface RawShaderMeta {
  /** Display title */
  title: string;
  /** Brief description of the shader effect */
  description: string;
  /** ISO 8601 date string (YYYY-MM-DD) */
  date: string;
  /** Categorization tags */
  tags: string[];
  /** External links */
  links: ShaderLinks;
  /** Optional channel wiring overrides */
  channels?: ShaderChannels;
}
